# adminlogin
# curl -X POST "https://game-shop-uz.herokuapp.com/api/auth/login" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"password\": \"111\", \"userName\": \"admin\"}"
POST https://game-shop-uz.herokuapp.com/api/auth/login
accept: */*
Content-Type: application/json

{
  "password": "111",
  "userName": "admin"
}

###


