
# all product
GET  http://localhost:3001/api/product
###

# find id
 GET http://localhost:3001/api/product/1
###

# categoriy
GET http://localhost:3001/api/product?category=
###

# search
GET http://localhost:3001/api/product?name=
###

# category
GET http://localhost:3001/api/category
###