import './globals.css'
import type { Metadata } from 'next'
import React from "react";
import {NavBar,Footer} from "@/components";


export const metadata: Metadata = {
  title: 'Car Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"relative"}>
      <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
