import './globals.css'
import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import NavBar from "@/components/NavBar";
import FooterBox from "@/components/FooterBox";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const montserrat = Montserrat({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={montserrat.className}>
        <NavBar/>
        <main className='container mx-auto'>
            {children}
        </main>
        <FooterBox/>
        <ToastContainer/>
        </body>
        </html>
    )
}
