const Data = [
    {
        id: 1,
        image: '/Gamecovers/cs_go.png',
        title: 'Counter-Strike: Global Offensive (CS:GO)',
        gener: "Шутер от первого лица, Шутер, Экшен, Тактик",
        description: 'Counter-Strike: Global Offensive (CS:GO) расширяет границы ураганной командной игры, представленной ещё 19 лет назад.CS:GO включает в себя новые карты, персонажей, оружие и режимы игры, а также улучшает классическую составляющую CS (de_dust2 и т. п.).',
        price: 10,
        video: 'https://youtu.be/edYCtaNueQY',
    },
    {
        id: 2,
        image: '/Gamecovers/dota2.jpg',
        title: 'Dota 2',
        gener: "Бесплатная игра, MOBA, Для нескольких игроков",
        description: 'Игра может похвастаться бесконечным разнообразием героев, способностей и предметов, благодаря чему каждый матч уникален. Любой герой может исполнять множество ролей, и для каждой нужды найдутся подходящие предметы. Здесь вас ничто не ограничивает — вы сами выбираете, какой стратегии следовать.',
        price: 40,
        video: 'https://youtu.be/-cSFPIwMEq4',
    },
    {
        id: 3,
        image: '/Gamecovers/forza.jpg',
        title: 'Forza Horizon 5',
        gener: "Гонки, Открытый мир, Вождение, Приключен",
        description: 'Вас ждёт бесконечный калейдоскоп приключений Horizon! Совершайте увлекательные поездки по невероятно красивому и самобытному миру Мексики за рулём величайших автомобилей в истории.',
        price: 27,
        video: 'https://youtu.be/FYH9n37B7Yw',
    },
    {
        id: 4,
        image: '/Gamecovers/elden.png',
        title: 'ELDEN RING',
        gener: "Похожа на Dark Souls, Расслабляющая, Сложная",
        description: 'НОВЫЙ ФЭНТЕЗИЙНЫЙ РОЛЕВОЙ БОЕВИК.Восстань, погасшая душа! Междуземье ждёт своего повелителя. Пусть благодать приведёт тебя к Кольцу Элден.',
        price: 34,
        video: 'https://youtu.be/OT8if6DXOFQ',
    },
    {
        id: 5,
        image: '/Gamecovers/cyberpunk.png',
        title: 'Cyberpunk 2077',
        gener: "Киберпанк, Открытый мир, Ролевая игра",
        description: 'Cyberpunk 2077 — приключенческая ролевая игра с открытым миром, рассказывающая о киберпанке-наёмнике Ви и борьбе за жизнь в мегаполисе Найт-Сити.',
        price: 23,
        video: 'https://youtu.be/8X2kIfS6fb8',
    },
];
export default Data;