const Data = [
    {
        id: 1,
        image: 'https://i.ibb.co/B29wMDB/cs-go.png',
        title: 'Counter-Strike:Global-Offensive(CS:GO)',
        gener: "Шутер от первого лица, Шутер, Экшен, Тактик",
        description: 'Counter-Strike: Global Offensive (CS:GO) расширяет границы ураганной командной игры, представленной ещё 19 лет назад.CS:GO включает в себя новые карты, персонажей, оружие и режимы игры, а также улучшает классическую составляющую CS (de_dust2 и т. п.).',
        price: 10,
        downtorr:'/cs_go.torrent',
        video: "https://www.youtube.com/embed/1nkO4N7P-Ys",
    },
    {
        id: 2,
        image: 'https://i.ibb.co/nDfJGH4/dota2.jpg',
        title: 'Dota-2',
        gener: "Бесплатная игра, MOBA, Для нескольких игроков",
        description: 'Игра может похвастаться бесконечным разнообразием героев, способностей и предметов, благодаря чему каждый матч уникален. Любой герой может исполнять множество ролей, и для каждой нужды найдутся подходящие предметы. Здесь вас ничто не ограничивает — вы сами выбираете, какой стратегии следовать.',
        price: 40,
        downtorr:'/dota_2.torrent',
        video: "https://www.youtube.com/embed/SmnqsdeHFT0",
    },
    {
        id: 3,
        image: 'https://i.ibb.co/CBTwYd6/forza.jpg',
        title: 'Forza-Horizon5',
        gener: "Гонки, Открытый мир, Вождение, Приключен",
        description: 'Вас ждёт бесконечный калейдоскоп приключений Horizon! Совершайте увлекательные поездки по невероятно красивому и самобытному миру Мексики за рулём величайших автомобилей в истории.',
        price: 27,
        downtorr:'/forza_harizon.torrent',
        video: "https://www.youtube.com/embed/FYH9n37B7Yw",
    },
    {
        id: 4,
        image: 'https://i.ibb.co/GM5MgwJ/elden.png',
        title: 'ELDEN-RING',
        gener: "Похожа на Dark Souls, Расслабляющая, Сложная",
        description: 'НОВЫЙ ФЭНТЕЗИЙНЫЙ РОЛЕВОЙ БОЕВИК.Восстань, погасшая душа! Междуземье ждёт своего повелителя. Пусть благодать приведёт тебя к Кольцу Элден.',
        price: 34,
        downtorr:'/elden_ring.torrent',
        video: "https://www.youtube.com/embed/K_03kFqWfqs",
    },
    {
        id: 5,
        image: 'https://i.ibb.co/MMf95sn/cyberpunk.png',
        title: 'Cyberpunk2077',
        gener: "Киберпанк, Открытый мир, Ролевая игра",
        description: 'Cyberpunk 2077 — приключенческая ролевая игра с открытым миром, рассказывающая о киберпанке-наёмнике Ви и борьбе за жизнь в мегаполисе Найт-Сити.',
        price: 23,
        downtorr:'/cyberpunk2077.torrent',
        video: "https://www.youtube.com/embed/P99qJGrPNLs",
    },
 {
        id: 6,
        image: 'https://i.ibb.co/3sBPZ6d/callofduty.jpg',
        title: 'Call of duty',
        gener: "Шутер от первого  лица, Шутер, Экшен, Тактик",
        description: 'Call of Duty — видеоигра-шутер от первого лица, основанная на id Tech 3 и выпущенная 29 октября 2003 года. Игра была разработана Infinity Ward и издана Activision. Игра имитирует пехотные и общевойсковые боевые действия Второй мировой войны.',
        price: 19,
        downtorr:'/cyberpunk2077.torrent',
        video: "https://www.youtube.com/embed/sduyPwuEPV0",
    },
];
export default Data;